server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?imooc_shiro
    username: root
    password: admin

